export const COUNTRIES = [
  {
    id: 1,
    createdAt: null,
    updatedAt: null,
    name: 'AFGHANISTAN',
    iso: 'AF',
    iso3: 'AFG',
    icon: null,
    numcode: 4,
    phoneCode: 93,
  },
  {
    id: 2,
    createdAt: null,
    updatedAt: null,
    name: 'ALBANIA',
    iso: 'AL',
    iso3: 'ALB',
    icon: null,
    numcode: 8,
    phoneCode: 355,
  },
  {
    id: 3,
    createdAt: null,
    updatedAt: null,
    name: 'ALGERIA',
    iso: 'DZ',
    iso3: 'DZA',
    icon: null,
    numcode: 12,
    phoneCode: 213,
  },
  {
    id: 4,
    createdAt: null,
    updatedAt: null,
    name: 'AMERICAN SAMOA',
    iso: 'AS',
    iso3: 'ASM',
    icon: null,
    numcode: 16,
    phoneCode: 1684,
  },
  {
    id: 5,
    createdAt: null,
    updatedAt: null,
    name: 'ANDORRA',
    iso: 'AD',
    iso3: 'AND',
    icon: null,
    numcode: 20,
    phoneCode: 376,
  },
  {
    id: 6,
    createdAt: null,
    updatedAt: null,
    name: 'ANGOLA',
    iso: 'AO',
    iso3: 'AGO',
    icon: null,
    numcode: 24,
    phoneCode: 244,
  },
  {
    id: 7,
    createdAt: null,
    updatedAt: null,
    name: 'ANGUILLA',
    iso: 'AI',
    iso3: 'AIA',
    icon: null,
    numcode: 660,
    phoneCode: 1264,
  },
  {
    id: 8,
    createdAt: null,
    updatedAt: null,
    name: 'ANTARCTICA',
    iso: 'AQ',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 0,
  },
  {
    id: 9,
    createdAt: null,
    updatedAt: null,
    name: 'ANTIGUA AND BARBUDA',
    iso: 'AG',
    iso3: 'ATG',
    icon: null,
    numcode: 28,
    phoneCode: 1268,
  },
  {
    id: 10,
    createdAt: null,
    updatedAt: null,
    name: 'ARGENTINA',
    iso: 'AR',
    iso3: 'ARG',
    icon: null,
    numcode: 32,
    phoneCode: 54,
  },
  {
    id: 11,
    createdAt: null,
    updatedAt: null,
    name: 'ARMENIA',
    iso: 'AM',
    iso3: 'ARM',
    icon: null,
    numcode: 51,
    phoneCode: 374,
  },
  {
    id: 12,
    createdAt: null,
    updatedAt: null,
    name: 'ARUBA',
    iso: 'AW',
    iso3: 'ABW',
    icon: null,
    numcode: 533,
    phoneCode: 297,
  },
  {
    id: 13,
    createdAt: null,
    updatedAt: null,
    name: 'AUSTRALIA',
    iso: 'AU',
    iso3: 'AUS',
    icon: null,
    numcode: 36,
    phoneCode: 61,
  },
  {
    id: 14,
    createdAt: null,
    updatedAt: null,
    name: 'AUSTRIA',
    iso: 'AT',
    iso3: 'AUT',
    icon: null,
    numcode: 40,
    phoneCode: 43,
  },
  {
    id: 15,
    createdAt: null,
    updatedAt: null,
    name: 'AZERBAIJAN',
    iso: 'AZ',
    iso3: 'AZE',
    icon: null,
    numcode: 31,
    phoneCode: 994,
  },
  {
    id: 16,
    createdAt: null,
    updatedAt: null,
    name: 'BAHAMAS',
    iso: 'BS',
    iso3: 'BHS',
    icon: null,
    numcode: 44,
    phoneCode: 1242,
  },
  {
    id: 17,
    createdAt: null,
    updatedAt: null,
    name: 'BAHRAIN',
    iso: 'BH',
    iso3: 'BHR',
    icon: null,
    numcode: 48,
    phoneCode: 973,
  },
  {
    id: 18,
    createdAt: null,
    updatedAt: null,
    name: 'BANGLADESH',
    iso: 'BD',
    iso3: 'BGD',
    icon: null,
    numcode: 50,
    phoneCode: 880,
  },
  {
    id: 19,
    createdAt: null,
    updatedAt: null,
    name: 'BARBADOS',
    iso: 'BB',
    iso3: 'BRB',
    icon: null,
    numcode: 52,
    phoneCode: 1246,
  },
  {
    id: 20,
    createdAt: null,
    updatedAt: null,
    name: 'BELARUS',
    iso: 'BY',
    iso3: 'BLR',
    icon: null,
    numcode: 112,
    phoneCode: 375,
  },
  {
    id: 21,
    createdAt: null,
    updatedAt: null,
    name: 'BELGIUM',
    iso: 'BE',
    iso3: 'BEL',
    icon: null,
    numcode: 56,
    phoneCode: 32,
  },
  {
    id: 22,
    createdAt: null,
    updatedAt: null,
    name: 'BELIZE',
    iso: 'BZ',
    iso3: 'BLZ',
    icon: null,
    numcode: 84,
    phoneCode: 501,
  },
  {
    id: 23,
    createdAt: null,
    updatedAt: null,
    name: 'BENIN',
    iso: 'BJ',
    iso3: 'BEN',
    icon: null,
    numcode: 204,
    phoneCode: 229,
  },
  {
    id: 24,
    createdAt: null,
    updatedAt: null,
    name: 'BERMUDA',
    iso: 'BM',
    iso3: 'BMU',
    icon: null,
    numcode: 60,
    phoneCode: 1441,
  },
  {
    id: 25,
    createdAt: null,
    updatedAt: null,
    name: 'BHUTAN',
    iso: 'BT',
    iso3: 'BTN',
    icon: null,
    numcode: 64,
    phoneCode: 975,
  },
  {
    id: 26,
    createdAt: null,
    updatedAt: null,
    name: 'BOLIVIA',
    iso: 'BO',
    iso3: 'BOL',
    icon: null,
    numcode: 68,
    phoneCode: 591,
  },
  {
    id: 27,
    createdAt: null,
    updatedAt: null,
    name: 'BOSNIA AND HERZEGOVINA',
    iso: 'BA',
    iso3: 'BIH',
    icon: null,
    numcode: 70,
    phoneCode: 387,
  },
  {
    id: 28,
    createdAt: null,
    updatedAt: null,
    name: 'BOTSWANA',
    iso: 'BW',
    iso3: 'BWA',
    icon: null,
    numcode: 72,
    phoneCode: 267,
  },
  {
    id: 29,
    createdAt: null,
    updatedAt: null,
    name: 'BOUVET ISLAND',
    iso: 'BV',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 0,
  },
  {
    id: 30,
    createdAt: null,
    updatedAt: null,
    name: 'BRAZIL',
    iso: 'BR',
    iso3: 'BRA',
    icon: null,
    numcode: 76,
    phoneCode: 55,
  },
  {
    id: 31,
    createdAt: null,
    updatedAt: null,
    name: 'BRITISH INDIAN OCEAN TERRITORY',
    iso: 'IO',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 246,
  },
  {
    id: 32,
    createdAt: null,
    updatedAt: null,
    name: 'BRUNEI DARUSSALAM',
    iso: 'BN',
    iso3: 'BRN',
    icon: null,
    numcode: 96,
    phoneCode: 673,
  },
  {
    id: 33,
    createdAt: null,
    updatedAt: null,
    name: 'BULGARIA',
    iso: 'BG',
    iso3: 'BGR',
    icon: null,
    numcode: 100,
    phoneCode: 359,
  },
  {
    id: 34,
    createdAt: null,
    updatedAt: null,
    name: 'BURKINA FASO',
    iso: 'BF',
    iso3: 'BFA',
    icon: null,
    numcode: 854,
    phoneCode: 226,
  },
  {
    id: 35,
    createdAt: null,
    updatedAt: null,
    name: 'BURUNDI',
    iso: 'BI',
    iso3: 'BDI',
    icon: null,
    numcode: 108,
    phoneCode: 257,
  },
  {
    id: 36,
    createdAt: null,
    updatedAt: null,
    name: 'CAMBODIA',
    iso: 'KH',
    iso3: 'KHM',
    icon: null,
    numcode: 116,
    phoneCode: 855,
  },
  {
    id: 37,
    createdAt: null,
    updatedAt: null,
    name: 'CAMEROON',
    iso: 'CM',
    iso3: 'CMR',
    icon: null,
    numcode: 120,
    phoneCode: 237,
  },
  {
    id: 38,
    createdAt: null,
    updatedAt: null,
    name: 'CANADA',
    iso: 'CA',
    iso3: 'CAN',
    icon: null,
    numcode: 124,
    phoneCode: 1,
  },
  {
    id: 39,
    createdAt: null,
    updatedAt: null,
    name: 'CAPE VERDE',
    iso: 'CV',
    iso3: 'CPV',
    icon: null,
    numcode: 132,
    phoneCode: 238,
  },
  {
    id: 40,
    createdAt: null,
    updatedAt: null,
    name: 'CAYMAN ISLANDS',
    iso: 'KY',
    iso3: 'CYM',
    icon: null,
    numcode: 136,
    phoneCode: 1345,
  },
  {
    id: 41,
    createdAt: null,
    updatedAt: null,
    name: 'CENTRAL AFRICAN REPUBLIC',
    iso: 'CF',
    iso3: 'CAF',
    icon: null,
    numcode: 140,
    phoneCode: 236,
  },
  {
    id: 42,
    createdAt: null,
    updatedAt: null,
    name: 'CHAD',
    iso: 'TD',
    iso3: 'TCD',
    icon: null,
    numcode: 148,
    phoneCode: 235,
  },
  {
    id: 43,
    createdAt: null,
    updatedAt: null,
    name: 'CHILE',
    iso: 'CL',
    iso3: 'CHL',
    icon: null,
    numcode: 152,
    phoneCode: 56,
  },
  {
    id: 44,
    createdAt: null,
    updatedAt: null,
    name: 'CHINA',
    iso: 'CN',
    iso3: 'CHN',
    icon: null,
    numcode: 156,
    phoneCode: 86,
  },
  {
    id: 45,
    createdAt: null,
    updatedAt: null,
    name: 'CHRISTMAS ISLAND',
    iso: 'CX',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 61,
  },
  {
    id: 46,
    createdAt: null,
    updatedAt: null,
    name: 'COCOS (KEELING) ISLANDS',
    iso: 'CC',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 672,
  },
  {
    id: 47,
    createdAt: null,
    updatedAt: null,
    name: 'COLOMBIA',
    iso: 'CO',
    iso3: 'COL',
    icon: null,
    numcode: 170,
    phoneCode: 57,
  },
  {
    id: 48,
    createdAt: null,
    updatedAt: null,
    name: 'COMOROS',
    iso: 'KM',
    iso3: 'COM',
    icon: null,
    numcode: 174,
    phoneCode: 269,
  },
  {
    id: 49,
    createdAt: null,
    updatedAt: null,
    name: 'CONGO',
    iso: 'CG',
    iso3: 'COG',
    icon: null,
    numcode: 178,
    phoneCode: 242,
  },
  {
    id: 50,
    createdAt: null,
    updatedAt: null,
    name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
    iso: 'CD',
    iso3: 'COD',
    icon: null,
    numcode: 180,
    phoneCode: 242,
  },
  {
    id: 51,
    createdAt: null,
    updatedAt: null,
    name: 'COOK ISLANDS',
    iso: 'CK',
    iso3: 'COK',
    icon: null,
    numcode: 184,
    phoneCode: 682,
  },
  {
    id: 52,
    createdAt: null,
    updatedAt: null,
    name: 'COSTA RICA',
    iso: 'CR',
    iso3: 'CRI',
    icon: null,
    numcode: 188,
    phoneCode: 506,
  },
  {
    id: 53,
    createdAt: null,
    updatedAt: null,
    name: "COTE D'IVOIRE",
    iso: 'CI',
    iso3: 'CIV',
    icon: null,
    numcode: 384,
    phoneCode: 225,
  },
  {
    id: 54,
    createdAt: null,
    updatedAt: null,
    name: 'CROATIA',
    iso: 'HR',
    iso3: 'HRV',
    icon: null,
    numcode: 191,
    phoneCode: 385,
  },
  {
    id: 55,
    createdAt: null,
    updatedAt: null,
    name: 'CUBA',
    iso: 'CU',
    iso3: 'CUB',
    icon: null,
    numcode: 192,
    phoneCode: 53,
  },
  {
    id: 56,
    createdAt: null,
    updatedAt: null,
    name: 'CYPRUS',
    iso: 'CY',
    iso3: 'CYP',
    icon: null,
    numcode: 196,
    phoneCode: 357,
  },
  {
    id: 57,
    createdAt: null,
    updatedAt: null,
    name: 'CZECH REPUBLIC',
    iso: 'CZ',
    iso3: 'CZE',
    icon: null,
    numcode: 203,
    phoneCode: 420,
  },
  {
    id: 58,
    createdAt: null,
    updatedAt: null,
    name: 'DENMARK',
    iso: 'DK',
    iso3: 'DNK',
    icon: null,
    numcode: 208,
    phoneCode: 45,
  },
  {
    id: 59,
    createdAt: null,
    updatedAt: null,
    name: 'DJIBOUTI',
    iso: 'DJ',
    iso3: 'DJI',
    icon: null,
    numcode: 262,
    phoneCode: 253,
  },
  {
    id: 60,
    createdAt: null,
    updatedAt: null,
    name: 'DOMINICA',
    iso: 'DM',
    iso3: 'DMA',
    icon: null,
    numcode: 212,
    phoneCode: 1767,
  },
  {
    id: 61,
    createdAt: null,
    updatedAt: null,
    name: 'DOMINICAN REPUBLIC',
    iso: 'DO',
    iso3: 'DOM',
    icon: null,
    numcode: 214,
    phoneCode: 1809,
  },
  {
    id: 62,
    createdAt: null,
    updatedAt: null,
    name: 'ECUADOR',
    iso: 'EC',
    iso3: 'ECU',
    icon: null,
    numcode: 218,
    phoneCode: 593,
  },
  {
    id: 63,
    createdAt: null,
    updatedAt: null,
    name: 'EGYPT',
    iso: 'EG',
    iso3: 'EGY',
    icon: null,
    numcode: 818,
    phoneCode: 20,
  },
  {
    id: 64,
    createdAt: null,
    updatedAt: null,
    name: 'EL SALVADOR',
    iso: 'SV',
    iso3: 'SLV',
    icon: null,
    numcode: 222,
    phoneCode: 503,
  },
  {
    id: 65,
    createdAt: null,
    updatedAt: null,
    name: 'EQUATORIAL GUINEA',
    iso: 'GQ',
    iso3: 'GNQ',
    icon: null,
    numcode: 226,
    phoneCode: 240,
  },
  {
    id: 66,
    createdAt: null,
    updatedAt: null,
    name: 'ERITREA',
    iso: 'ER',
    iso3: 'ERI',
    icon: null,
    numcode: 232,
    phoneCode: 291,
  },
  {
    id: 67,
    createdAt: null,
    updatedAt: null,
    name: 'ESTONIA',
    iso: 'EE',
    iso3: 'EST',
    icon: null,
    numcode: 233,
    phoneCode: 372,
  },
  {
    id: 68,
    createdAt: null,
    updatedAt: null,
    name: 'ETHIOPIA',
    iso: 'ET',
    iso3: 'ETH',
    icon: null,
    numcode: 231,
    phoneCode: 251,
  },
  {
    id: 69,
    createdAt: null,
    updatedAt: null,
    name: 'FALKLAND ISLANDS (MALVINAS)',
    iso: 'FK',
    iso3: 'FLK',
    icon: null,
    numcode: 238,
    phoneCode: 500,
  },
  {
    id: 70,
    createdAt: null,
    updatedAt: null,
    name: 'FAROE ISLANDS',
    iso: 'FO',
    iso3: 'FRO',
    icon: null,
    numcode: 234,
    phoneCode: 298,
  },
  {
    id: 71,
    createdAt: null,
    updatedAt: null,
    name: 'FIJI',
    iso: 'FJ',
    iso3: 'FJI',
    icon: null,
    numcode: 242,
    phoneCode: 679,
  },
  {
    id: 72,
    createdAt: null,
    updatedAt: null,
    name: 'FINLAND',
    iso: 'FI',
    iso3: 'FIN',
    icon: null,
    numcode: 246,
    phoneCode: 358,
  },
  {
    id: 73,
    createdAt: null,
    updatedAt: null,
    name: 'FRANCE',
    iso: 'FR',
    iso3: 'FRA',
    icon: null,
    numcode: 250,
    phoneCode: 33,
  },
  {
    id: 74,
    createdAt: null,
    updatedAt: null,
    name: 'FRENCH GUIANA',
    iso: 'GF',
    iso3: 'GUF',
    icon: null,
    numcode: 254,
    phoneCode: 594,
  },
  {
    id: 75,
    createdAt: null,
    updatedAt: null,
    name: 'FRENCH POLYNESIA',
    iso: 'PF',
    iso3: 'PYF',
    icon: null,
    numcode: 258,
    phoneCode: 689,
  },
  {
    id: 76,
    createdAt: null,
    updatedAt: null,
    name: 'FRENCH SOUTHERN TERRITORIES',
    iso: 'TF',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 0,
  },
  {
    id: 77,
    createdAt: null,
    updatedAt: null,
    name: 'GABON',
    iso: 'GA',
    iso3: 'GAB',
    icon: null,
    numcode: 266,
    phoneCode: 241,
  },
  {
    id: 78,
    createdAt: null,
    updatedAt: null,
    name: 'GAMBIA',
    iso: 'GM',
    iso3: 'GMB',
    icon: null,
    numcode: 270,
    phoneCode: 220,
  },
  {
    id: 79,
    createdAt: null,
    updatedAt: null,
    name: 'GEORGIA',
    iso: 'GE',
    iso3: 'GEO',
    icon: null,
    numcode: 268,
    phoneCode: 995,
  },
  {
    id: 80,
    createdAt: null,
    updatedAt: null,
    name: 'GERMANY',
    iso: 'DE',
    iso3: 'DEU',
    icon: null,
    numcode: 276,
    phoneCode: 49,
  },
  {
    id: 81,
    createdAt: null,
    updatedAt: null,
    name: 'GHANA',
    iso: 'GH',
    iso3: 'GHA',
    icon: null,
    numcode: 288,
    phoneCode: 233,
  },
  {
    id: 82,
    createdAt: null,
    updatedAt: null,
    name: 'GIBRALTAR',
    iso: 'GI',
    iso3: 'GIB',
    icon: null,
    numcode: 292,
    phoneCode: 350,
  },
  {
    id: 83,
    createdAt: null,
    updatedAt: null,
    name: 'GREECE',
    iso: 'GR',
    iso3: 'GRC',
    icon: null,
    numcode: 300,
    phoneCode: 30,
  },
  {
    id: 84,
    createdAt: null,
    updatedAt: null,
    name: 'GREENLAND',
    iso: 'GL',
    iso3: 'GRL',
    icon: null,
    numcode: 304,
    phoneCode: 299,
  },
  {
    id: 85,
    createdAt: null,
    updatedAt: null,
    name: 'GRENADA',
    iso: 'GD',
    iso3: 'GRD',
    icon: null,
    numcode: 308,
    phoneCode: 1473,
  },
  {
    id: 86,
    createdAt: null,
    updatedAt: null,
    name: 'GUADELOUPE',
    iso: 'GP',
    iso3: 'GLP',
    icon: null,
    numcode: 312,
    phoneCode: 590,
  },
  {
    id: 87,
    createdAt: null,
    updatedAt: null,
    name: 'GUAM',
    iso: 'GU',
    iso3: 'GUM',
    icon: null,
    numcode: 316,
    phoneCode: 1671,
  },
  {
    id: 88,
    createdAt: null,
    updatedAt: null,
    name: 'GUATEMALA',
    iso: 'GT',
    iso3: 'GTM',
    icon: null,
    numcode: 320,
    phoneCode: 502,
  },
  {
    id: 89,
    createdAt: null,
    updatedAt: null,
    name: 'GUINEA',
    iso: 'GN',
    iso3: 'GIN',
    icon: null,
    numcode: 324,
    phoneCode: 224,
  },
  {
    id: 90,
    createdAt: null,
    updatedAt: null,
    name: 'GUINEA-BISSAU',
    iso: 'GW',
    iso3: 'GNB',
    icon: null,
    numcode: 624,
    phoneCode: 245,
  },
  {
    id: 91,
    createdAt: null,
    updatedAt: null,
    name: 'GUYANA',
    iso: 'GY',
    iso3: 'GUY',
    icon: null,
    numcode: 328,
    phoneCode: 592,
  },
  {
    id: 92,
    createdAt: null,
    updatedAt: null,
    name: 'HAITI',
    iso: 'HT',
    iso3: 'HTI',
    icon: null,
    numcode: 332,
    phoneCode: 509,
  },
  {
    id: 93,
    createdAt: null,
    updatedAt: null,
    name: 'HEARD ISLAND AND MCDONALD ISLANDS',
    iso: 'HM',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 0,
  },
  {
    id: 94,
    createdAt: null,
    updatedAt: null,
    name: 'HOLY SEE (VATICAN CITY STATE)',
    iso: 'VA',
    iso3: 'VAT',
    icon: null,
    numcode: 336,
    phoneCode: 39,
  },
  {
    id: 95,
    createdAt: null,
    updatedAt: null,
    name: 'HONDURAS',
    iso: 'HN',
    iso3: 'HND',
    icon: null,
    numcode: 340,
    phoneCode: 504,
  },
  {
    id: 96,
    createdAt: null,
    updatedAt: null,
    name: 'HONG KONG',
    iso: 'HK',
    iso3: 'HKG',
    icon: null,
    numcode: 344,
    phoneCode: 852,
  },
  {
    id: 97,
    createdAt: null,
    updatedAt: null,
    name: 'HUNGARY',
    iso: 'HU',
    iso3: 'HUN',
    icon: null,
    numcode: 348,
    phoneCode: 36,
  },
  {
    id: 98,
    createdAt: null,
    updatedAt: null,
    name: 'ICELAND',
    iso: 'IS',
    iso3: 'ISL',
    icon: null,
    numcode: 352,
    phoneCode: 354,
  },
  {
    id: 99,
    createdAt: null,
    updatedAt: null,
    name: 'INDIA',
    iso: 'IN',
    iso3: 'IND',
    icon: null,
    numcode: 356,
    phoneCode: 91,
  },
  {
    id: 100,
    createdAt: null,
    updatedAt: null,
    name: 'INDONESIA',
    iso: 'ID',
    iso3: 'IDN',
    icon: null,
    numcode: 360,
    phoneCode: 62,
  },
  {
    id: 101,
    createdAt: null,
    updatedAt: null,
    name: 'IRAN, ISLAMIC REPUBLIC OF',
    iso: 'IR',
    iso3: 'IRN',
    icon: null,
    numcode: 364,
    phoneCode: 98,
  },
  {
    id: 102,
    createdAt: null,
    updatedAt: null,
    name: 'IRAQ',
    iso: 'IQ',
    iso3: 'IRQ',
    icon: null,
    numcode: 368,
    phoneCode: 964,
  },
  {
    id: 103,
    createdAt: null,
    updatedAt: null,
    name: 'IRELAND',
    iso: 'IE',
    iso3: 'IRL',
    icon: null,
    numcode: 372,
    phoneCode: 353,
  },
  {
    id: 104,
    createdAt: null,
    updatedAt: null,
    name: 'ISRAEL',
    iso: 'IL',
    iso3: 'ISR',
    icon: null,
    numcode: 376,
    phoneCode: 972,
  },
  {
    id: 105,
    createdAt: null,
    updatedAt: null,
    name: 'ITALY',
    iso: 'IT',
    iso3: 'ITA',
    icon: null,
    numcode: 380,
    phoneCode: 39,
  },
  {
    id: 106,
    createdAt: null,
    updatedAt: null,
    name: 'JAMAICA',
    iso: 'JM',
    iso3: 'JAM',
    icon: null,
    numcode: 388,
    phoneCode: 1876,
  },
  {
    id: 107,
    createdAt: null,
    updatedAt: null,
    name: 'JAPAN',
    iso: 'JP',
    iso3: 'JPN',
    icon: null,
    numcode: 392,
    phoneCode: 81,
  },
  {
    id: 108,
    createdAt: null,
    updatedAt: null,
    name: 'JORDAN',
    iso: 'JO',
    iso3: 'JOR',
    icon: null,
    numcode: 400,
    phoneCode: 962,
  },
  {
    id: 109,
    createdAt: null,
    updatedAt: null,
    name: 'KAZAKHSTAN',
    iso: 'KZ',
    iso3: 'KAZ',
    icon: null,
    numcode: 398,
    phoneCode: 7,
  },
  {
    id: 110,
    createdAt: null,
    updatedAt: null,
    name: 'KENYA',
    iso: 'KE',
    iso3: 'KEN',
    icon: null,
    numcode: 404,
    phoneCode: 254,
  },
  {
    id: 111,
    createdAt: null,
    updatedAt: null,
    name: 'KIRIBATI',
    iso: 'KI',
    iso3: 'KIR',
    icon: null,
    numcode: 296,
    phoneCode: 686,
  },
  {
    id: 112,
    createdAt: null,
    updatedAt: null,
    name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    iso: 'KP',
    iso3: 'PRK',
    icon: null,
    numcode: 408,
    phoneCode: 850,
  },
  {
    id: 113,
    createdAt: null,
    updatedAt: null,
    name: 'KOREA, REPUBLIC OF',
    iso: 'KR',
    iso3: 'KOR',
    icon: null,
    numcode: 410,
    phoneCode: 82,
  },
  {
    id: 114,
    createdAt: null,
    updatedAt: null,
    name: 'KUWAIT',
    iso: 'KW',
    iso3: 'KWT',
    icon: null,
    numcode: 414,
    phoneCode: 965,
  },
  {
    id: 115,
    createdAt: null,
    updatedAt: null,
    name: 'KYRGYZSTAN',
    iso: 'KG',
    iso3: 'KGZ',
    icon: null,
    numcode: 417,
    phoneCode: 996,
  },
  {
    id: 116,
    createdAt: null,
    updatedAt: null,
    name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    iso: 'LA',
    iso3: 'LAO',
    icon: null,
    numcode: 418,
    phoneCode: 856,
  },
  {
    id: 117,
    createdAt: null,
    updatedAt: null,
    name: 'LATVIA',
    iso: 'LV',
    iso3: 'LVA',
    icon: null,
    numcode: 428,
    phoneCode: 371,
  },
  {
    id: 118,
    createdAt: null,
    updatedAt: null,
    name: 'LEBANON',
    iso: 'LB',
    iso3: 'LBN',
    icon: null,
    numcode: 422,
    phoneCode: 961,
  },
  {
    id: 119,
    createdAt: null,
    updatedAt: null,
    name: 'LESOTHO',
    iso: 'LS',
    iso3: 'LSO',
    icon: null,
    numcode: 426,
    phoneCode: 266,
  },
  {
    id: 120,
    createdAt: null,
    updatedAt: null,
    name: 'LIBERIA',
    iso: 'LR',
    iso3: 'LBR',
    icon: null,
    numcode: 430,
    phoneCode: 231,
  },
  {
    id: 121,
    createdAt: null,
    updatedAt: null,
    name: 'LIBYAN ARAB JAMAHIRIYA',
    iso: 'LY',
    iso3: 'LBY',
    icon: null,
    numcode: 434,
    phoneCode: 218,
  },
  {
    id: 122,
    createdAt: null,
    updatedAt: null,
    name: 'LIECHTENSTEIN',
    iso: 'LI',
    iso3: 'LIE',
    icon: null,
    numcode: 438,
    phoneCode: 423,
  },
  {
    id: 123,
    createdAt: null,
    updatedAt: null,
    name: 'LITHUANIA',
    iso: 'LT',
    iso3: 'LTU',
    icon: null,
    numcode: 440,
    phoneCode: 370,
  },
  {
    id: 124,
    createdAt: null,
    updatedAt: null,
    name: 'LUXEMBOURG',
    iso: 'LU',
    iso3: 'LUX',
    icon: null,
    numcode: 442,
    phoneCode: 352,
  },
  {
    id: 125,
    createdAt: null,
    updatedAt: null,
    name: 'MACAO',
    iso: 'MO',
    iso3: 'MAC',
    icon: null,
    numcode: 446,
    phoneCode: 853,
  },
  {
    id: 126,
    createdAt: null,
    updatedAt: null,
    name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
    iso: 'MK',
    iso3: 'MKD',
    icon: null,
    numcode: 807,
    phoneCode: 389,
  },
  {
    id: 127,
    createdAt: null,
    updatedAt: null,
    name: 'MADAGASCAR',
    iso: 'MG',
    iso3: 'MDG',
    icon: null,
    numcode: 450,
    phoneCode: 261,
  },
  {
    id: 128,
    createdAt: null,
    updatedAt: null,
    name: 'MALAWI',
    iso: 'MW',
    iso3: 'MWI',
    icon: null,
    numcode: 454,
    phoneCode: 265,
  },
  {
    id: 129,
    createdAt: null,
    updatedAt: null,
    name: 'MALAYSIA',
    iso: 'MY',
    iso3: 'MYS',
    icon: null,
    numcode: 458,
    phoneCode: 60,
  },
  {
    id: 130,
    createdAt: null,
    updatedAt: null,
    name: 'MALDIVES',
    iso: 'MV',
    iso3: 'MDV',
    icon: null,
    numcode: 462,
    phoneCode: 960,
  },
  {
    id: 131,
    createdAt: null,
    updatedAt: null,
    name: 'MALI',
    iso: 'ML',
    iso3: 'MLI',
    icon: null,
    numcode: 466,
    phoneCode: 223,
  },
  {
    id: 132,
    createdAt: null,
    updatedAt: null,
    name: 'MALTA',
    iso: 'MT',
    iso3: 'MLT',
    icon: null,
    numcode: 470,
    phoneCode: 356,
  },
  {
    id: 133,
    createdAt: null,
    updatedAt: null,
    name: 'MARSHALL ISLANDS',
    iso: 'MH',
    iso3: 'MHL',
    icon: null,
    numcode: 584,
    phoneCode: 692,
  },
  {
    id: 134,
    createdAt: null,
    updatedAt: null,
    name: 'MARTINIQUE',
    iso: 'MQ',
    iso3: 'MTQ',
    icon: null,
    numcode: 474,
    phoneCode: 596,
  },
  {
    id: 135,
    createdAt: null,
    updatedAt: null,
    name: 'MAURITANIA',
    iso: 'MR',
    iso3: 'MRT',
    icon: null,
    numcode: 478,
    phoneCode: 222,
  },
  {
    id: 136,
    createdAt: null,
    updatedAt: null,
    name: 'MAURITIUS',
    iso: 'MU',
    iso3: 'MUS',
    icon: null,
    numcode: 480,
    phoneCode: 230,
  },
  {
    id: 137,
    createdAt: null,
    updatedAt: null,
    name: 'MAYOTTE',
    iso: 'YT',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 269,
  },
  {
    id: 138,
    createdAt: null,
    updatedAt: null,
    name: 'MEXICO',
    iso: 'MX',
    iso3: 'MEX',
    icon: null,
    numcode: 484,
    phoneCode: 52,
  },
  {
    id: 139,
    createdAt: null,
    updatedAt: null,
    name: 'MICRONESIA, FEDERATED STATES OF',
    iso: 'FM',
    iso3: 'FSM',
    icon: null,
    numcode: 583,
    phoneCode: 691,
  },
  {
    id: 140,
    createdAt: null,
    updatedAt: null,
    name: 'MOLDOVA, REPUBLIC OF',
    iso: 'MD',
    iso3: 'MDA',
    icon: null,
    numcode: 498,
    phoneCode: 373,
  },
  {
    id: 141,
    createdAt: null,
    updatedAt: null,
    name: 'MONACO',
    iso: 'MC',
    iso3: 'MCO',
    icon: null,
    numcode: 492,
    phoneCode: 377,
  },
  {
    id: 142,
    createdAt: null,
    updatedAt: null,
    name: 'MONGOLIA',
    iso: 'MN',
    iso3: 'MNG',
    icon: null,
    numcode: 496,
    phoneCode: 976,
  },
  {
    id: 143,
    createdAt: null,
    updatedAt: null,
    name: 'MONTSERRAT',
    iso: 'MS',
    iso3: 'MSR',
    icon: null,
    numcode: 500,
    phoneCode: 1664,
  },
  {
    id: 144,
    createdAt: null,
    updatedAt: null,
    name: 'MOROCCO',
    iso: 'MA',
    iso3: 'MAR',
    icon: null,
    numcode: 504,
    phoneCode: 212,
  },
  {
    id: 145,
    createdAt: null,
    updatedAt: null,
    name: 'MOZAMBIQUE',
    iso: 'MZ',
    iso3: 'MOZ',
    icon: null,
    numcode: 508,
    phoneCode: 258,
  },
  {
    id: 146,
    createdAt: null,
    updatedAt: null,
    name: 'MYANMAR',
    iso: 'MM',
    iso3: 'MMR',
    icon: null,
    numcode: 104,
    phoneCode: 95,
  },
  {
    id: 147,
    createdAt: null,
    updatedAt: null,
    name: 'NAMIBIA',
    iso: 'NA',
    iso3: 'NAM',
    icon: null,
    numcode: 516,
    phoneCode: 264,
  },
  {
    id: 148,
    createdAt: null,
    updatedAt: null,
    name: 'NAURU',
    iso: 'NR',
    iso3: 'NRU',
    icon: null,
    numcode: 520,
    phoneCode: 674,
  },
  {
    id: 149,
    createdAt: null,
    updatedAt: null,
    name: 'NEPAL',
    iso: 'NP',
    iso3: 'NPL',
    icon: null,
    numcode: 524,
    phoneCode: 977,
  },
  {
    id: 150,
    createdAt: null,
    updatedAt: null,
    name: 'NETHERLANDS',
    iso: 'NL',
    iso3: 'NLD',
    icon: null,
    numcode: 528,
    phoneCode: 31,
  },
  {
    id: 151,
    createdAt: null,
    updatedAt: null,
    name: 'NETHERLANDS ANTILLES',
    iso: 'AN',
    iso3: 'ANT',
    icon: null,
    numcode: 530,
    phoneCode: 599,
  },
  {
    id: 152,
    createdAt: null,
    updatedAt: null,
    name: 'NEW CALEDONIA',
    iso: 'NC',
    iso3: 'NCL',
    icon: null,
    numcode: 540,
    phoneCode: 687,
  },
  {
    id: 153,
    createdAt: null,
    updatedAt: null,
    name: 'NEW ZEALAND',
    iso: 'NZ',
    iso3: 'NZL',
    icon: null,
    numcode: 554,
    phoneCode: 64,
  },
  {
    id: 154,
    createdAt: null,
    updatedAt: null,
    name: 'NICARAGUA',
    iso: 'NI',
    iso3: 'NIC',
    icon: null,
    numcode: 558,
    phoneCode: 505,
  },
  {
    id: 155,
    createdAt: null,
    updatedAt: null,
    name: 'NIGER',
    iso: 'NE',
    iso3: 'NER',
    icon: null,
    numcode: 562,
    phoneCode: 227,
  },
  {
    id: 156,
    createdAt: null,
    updatedAt: null,
    name: 'NIGERIA',
    iso: 'NG',
    iso3: 'NGA',
    icon: null,
    numcode: 566,
    phoneCode: 234,
  },
  {
    id: 157,
    createdAt: null,
    updatedAt: null,
    name: 'NIUE',
    iso: 'NU',
    iso3: 'NIU',
    icon: null,
    numcode: 570,
    phoneCode: 683,
  },
  {
    id: 158,
    createdAt: null,
    updatedAt: null,
    name: 'NORFOLK ISLAND',
    iso: 'NF',
    iso3: 'NFK',
    icon: null,
    numcode: 574,
    phoneCode: 672,
  },
  {
    id: 159,
    createdAt: null,
    updatedAt: null,
    name: 'NORTHERN MARIANA ISLANDS',
    iso: 'MP',
    iso3: 'MNP',
    icon: null,
    numcode: 580,
    phoneCode: 1670,
  },
  {
    id: 160,
    createdAt: null,
    updatedAt: null,
    name: 'NORWAY',
    iso: 'NO',
    iso3: 'NOR',
    icon: null,
    numcode: 578,
    phoneCode: 47,
  },
  {
    id: 161,
    createdAt: null,
    updatedAt: null,
    name: 'OMAN',
    iso: 'OM',
    iso3: 'OMN',
    icon: null,
    numcode: 512,
    phoneCode: 968,
  },
  {
    id: 162,
    createdAt: null,
    updatedAt: null,
    name: 'PAKISTAN',
    iso: 'PK',
    iso3: 'PAK',
    icon: null,
    numcode: 586,
    phoneCode: 92,
  },
  {
    id: 163,
    createdAt: null,
    updatedAt: null,
    name: 'PALAU',
    iso: 'PW',
    iso3: 'PLW',
    icon: null,
    numcode: 585,
    phoneCode: 680,
  },
  {
    id: 164,
    createdAt: null,
    updatedAt: null,
    name: 'PALESTINIAN TERRITORY, OCCUPIED',
    iso: 'PS',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 970,
  },
  {
    id: 165,
    createdAt: null,
    updatedAt: null,
    name: 'PANAMA',
    iso: 'PA',
    iso3: 'PAN',
    icon: null,
    numcode: 591,
    phoneCode: 507,
  },
  {
    id: 166,
    createdAt: null,
    updatedAt: null,
    name: 'PAPUA NEW GUINEA',
    iso: 'PG',
    iso3: 'PNG',
    icon: null,
    numcode: 598,
    phoneCode: 675,
  },
  {
    id: 167,
    createdAt: null,
    updatedAt: null,
    name: 'PARAGUAY',
    iso: 'PY',
    iso3: 'PRY',
    icon: null,
    numcode: 600,
    phoneCode: 595,
  },
  {
    id: 168,
    createdAt: null,
    updatedAt: null,
    name: 'PERU',
    iso: 'PE',
    iso3: 'PER',
    icon: null,
    numcode: 604,
    phoneCode: 51,
  },
  {
    id: 169,
    createdAt: null,
    updatedAt: null,
    name: 'PHILIPPINES',
    iso: 'PH',
    iso3: 'PHL',
    icon: null,
    numcode: 608,
    phoneCode: 63,
  },
  {
    id: 170,
    createdAt: null,
    updatedAt: null,
    name: 'PITCAIRN',
    iso: 'PN',
    iso3: 'PCN',
    icon: null,
    numcode: 612,
    phoneCode: 0,
  },
  {
    id: 171,
    createdAt: null,
    updatedAt: null,
    name: 'POLAND',
    iso: 'PL',
    iso3: 'POL',
    icon: null,
    numcode: 616,
    phoneCode: 48,
  },
  {
    id: 172,
    createdAt: null,
    updatedAt: null,
    name: 'PORTUGAL',
    iso: 'PT',
    iso3: 'PRT',
    icon: null,
    numcode: 620,
    phoneCode: 351,
  },
  {
    id: 173,
    createdAt: null,
    updatedAt: null,
    name: 'PUERTO RICO',
    iso: 'PR',
    iso3: 'PRI',
    icon: null,
    numcode: 630,
    phoneCode: 1787,
  },
  {
    id: 174,
    createdAt: null,
    updatedAt: null,
    name: 'QATAR',
    iso: 'QA',
    iso3: 'QAT',
    icon: null,
    numcode: 634,
    phoneCode: 974,
  },
  {
    id: 175,
    createdAt: null,
    updatedAt: null,
    name: 'REUNION',
    iso: 'RE',
    iso3: 'REU',
    icon: null,
    numcode: 638,
    phoneCode: 262,
  },
  {
    id: 176,
    createdAt: null,
    updatedAt: null,
    name: 'ROMANIA',
    iso: 'RO',
    iso3: 'ROM',
    icon: null,
    numcode: 642,
    phoneCode: 40,
  },
  {
    id: 177,
    createdAt: null,
    updatedAt: null,
    name: 'RUSSIAN FEDERATION',
    iso: 'RU',
    iso3: 'RUS',
    icon: null,
    numcode: 643,
    phoneCode: 70,
  },
  {
    id: 178,
    createdAt: null,
    updatedAt: null,
    name: 'RWANDA',
    iso: 'RW',
    iso3: 'RWA',
    icon: null,
    numcode: 646,
    phoneCode: 250,
  },
  {
    id: 179,
    createdAt: null,
    updatedAt: null,
    name: 'SAINT HELENA',
    iso: 'SH',
    iso3: 'SHN',
    icon: null,
    numcode: 654,
    phoneCode: 290,
  },
  {
    id: 180,
    createdAt: null,
    updatedAt: null,
    name: 'SAINT KITTS AND NEVIS',
    iso: 'KN',
    iso3: 'KNA',
    icon: null,
    numcode: 659,
    phoneCode: 1869,
  },
  {
    id: 181,
    createdAt: null,
    updatedAt: null,
    name: 'SAINT LUCIA',
    iso: 'LC',
    iso3: 'LCA',
    icon: null,
    numcode: 662,
    phoneCode: 1758,
  },
  {
    id: 182,
    createdAt: null,
    updatedAt: null,
    name: 'SAINT PIERRE AND MIQUELON',
    iso: 'PM',
    iso3: 'SPM',
    icon: null,
    numcode: 666,
    phoneCode: 508,
  },
  {
    id: 183,
    createdAt: null,
    updatedAt: null,
    name: 'SAINT VINCENT AND THE GRENADINES',
    iso: 'VC',
    iso3: 'VCT',
    icon: null,
    numcode: 670,
    phoneCode: 1784,
  },
  {
    id: 184,
    createdAt: null,
    updatedAt: null,
    name: 'SAMOA',
    iso: 'WS',
    iso3: 'WSM',
    icon: null,
    numcode: 882,
    phoneCode: 684,
  },
  {
    id: 185,
    createdAt: null,
    updatedAt: null,
    name: 'SAN MARINO',
    iso: 'SM',
    iso3: 'SMR',
    icon: null,
    numcode: 674,
    phoneCode: 378,
  },
  {
    id: 186,
    createdAt: null,
    updatedAt: null,
    name: 'SAO TOME AND PRINCIPE',
    iso: 'ST',
    iso3: 'STP',
    icon: null,
    numcode: 678,
    phoneCode: 239,
  },
  {
    id: 187,
    createdAt: null,
    updatedAt: null,
    name: 'SAUDI ARABIA',
    iso: 'SA',
    iso3: 'SAU',
    icon: null,
    numcode: 682,
    phoneCode: 966,
  },
  {
    id: 188,
    createdAt: null,
    updatedAt: null,
    name: 'SENEGAL',
    iso: 'SN',
    iso3: 'SEN',
    icon: null,
    numcode: 686,
    phoneCode: 221,
  },
  {
    id: 189,
    createdAt: null,
    updatedAt: null,
    name: 'SERBIA AND MONTENEGRO',
    iso: 'CS',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 381,
  },
  {
    id: 190,
    createdAt: null,
    updatedAt: null,
    name: 'SEYCHELLES',
    iso: 'SC',
    iso3: 'SYC',
    icon: null,
    numcode: 690,
    phoneCode: 248,
  },
  {
    id: 191,
    createdAt: null,
    updatedAt: null,
    name: 'SIERRA LEONE',
    iso: 'SL',
    iso3: 'SLE',
    icon: null,
    numcode: 694,
    phoneCode: 232,
  },
  {
    id: 192,
    createdAt: null,
    updatedAt: null,
    name: 'SINGAPORE',
    iso: 'SG',
    iso3: 'SGP',
    icon: null,
    numcode: 702,
    phoneCode: 65,
  },
  {
    id: 193,
    createdAt: null,
    updatedAt: null,
    name: 'SLOVAKIA',
    iso: 'SK',
    iso3: 'SVK',
    icon: null,
    numcode: 703,
    phoneCode: 421,
  },
  {
    id: 194,
    createdAt: null,
    updatedAt: null,
    name: 'SLOVENIA',
    iso: 'SI',
    iso3: 'SVN',
    icon: null,
    numcode: 705,
    phoneCode: 386,
  },
  {
    id: 195,
    createdAt: null,
    updatedAt: null,
    name: 'SOLOMON ISLANDS',
    iso: 'SB',
    iso3: 'SLB',
    icon: null,
    numcode: 90,
    phoneCode: 677,
  },
  {
    id: 196,
    createdAt: null,
    updatedAt: null,
    name: 'SOMALIA',
    iso: 'SO',
    iso3: 'SOM',
    icon: null,
    numcode: 706,
    phoneCode: 252,
  },
  {
    id: 197,
    createdAt: null,
    updatedAt: null,
    name: 'SOUTH AFRICA',
    iso: 'ZA',
    iso3: 'ZAF',
    icon: null,
    numcode: 710,
    phoneCode: 27,
  },
  {
    id: 198,
    createdAt: null,
    updatedAt: null,
    name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    iso: 'GS',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 0,
  },
  {
    id: 199,
    createdAt: null,
    updatedAt: null,
    name: 'SPAIN',
    iso: 'ES',
    iso3: 'ESP',
    icon: null,
    numcode: 724,
    phoneCode: 34,
  },
  {
    id: 200,
    createdAt: null,
    updatedAt: null,
    name: 'SRI LANKA',
    iso: 'LK',
    iso3: 'LKA',
    icon: null,
    numcode: 144,
    phoneCode: 94,
  },
  {
    id: 201,
    createdAt: null,
    updatedAt: null,
    name: 'SUDAN',
    iso: 'SD',
    iso3: 'SDN',
    icon: null,
    numcode: 736,
    phoneCode: 249,
  },
  {
    id: 202,
    createdAt: null,
    updatedAt: null,
    name: 'SURINAME',
    iso: 'SR',
    iso3: 'SUR',
    icon: null,
    numcode: 740,
    phoneCode: 597,
  },
  {
    id: 203,
    createdAt: null,
    updatedAt: null,
    name: 'SVALBARD AND JAN MAYEN',
    iso: 'SJ',
    iso3: 'SJM',
    icon: null,
    numcode: 744,
    phoneCode: 47,
  },
  {
    id: 204,
    createdAt: null,
    updatedAt: null,
    name: 'SWAZILAND',
    iso: 'SZ',
    iso3: 'SWZ',
    icon: null,
    numcode: 748,
    phoneCode: 268,
  },
  {
    id: 205,
    createdAt: null,
    updatedAt: null,
    name: 'SWEDEN',
    iso: 'SE',
    iso3: 'SWE',
    icon: null,
    numcode: 752,
    phoneCode: 46,
  },
  {
    id: 206,
    createdAt: null,
    updatedAt: null,
    name: 'SWITZERLAND',
    iso: 'CH',
    iso3: 'CHE',
    icon: null,
    numcode: 756,
    phoneCode: 41,
  },
  {
    id: 207,
    createdAt: null,
    updatedAt: null,
    name: 'SYRIAN ARAB REPUBLIC',
    iso: 'SY',
    iso3: 'SYR',
    icon: null,
    numcode: 760,
    phoneCode: 963,
  },
  {
    id: 208,
    createdAt: null,
    updatedAt: null,
    name: 'TAIWAN, PROVINCE OF CHINA',
    iso: 'TW',
    iso3: 'TWN',
    icon: null,
    numcode: 158,
    phoneCode: 886,
  },
  {
    id: 209,
    createdAt: null,
    updatedAt: null,
    name: 'TAJIKISTAN',
    iso: 'TJ',
    iso3: 'TJK',
    icon: null,
    numcode: 762,
    phoneCode: 992,
  },
  {
    id: 210,
    createdAt: null,
    updatedAt: null,
    name: 'TANZANIA, UNITED REPUBLIC OF',
    iso: 'TZ',
    iso3: 'TZA',
    icon: null,
    numcode: 834,
    phoneCode: 255,
  },
  {
    id: 211,
    createdAt: null,
    updatedAt: null,
    name: 'THAILAND',
    iso: 'TH',
    iso3: 'THA',
    icon: null,
    numcode: 764,
    phoneCode: 66,
  },
  {
    id: 212,
    createdAt: null,
    updatedAt: null,
    name: 'TIMOR-LESTE',
    iso: 'TL',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 670,
  },
  {
    id: 213,
    createdAt: null,
    updatedAt: null,
    name: 'TOGO',
    iso: 'TG',
    iso3: 'TGO',
    icon: null,
    numcode: 768,
    phoneCode: 228,
  },
  {
    id: 214,
    createdAt: null,
    updatedAt: null,
    name: 'TOKELAU',
    iso: 'TK',
    iso3: 'TKL',
    icon: null,
    numcode: 772,
    phoneCode: 690,
  },
  {
    id: 215,
    createdAt: null,
    updatedAt: null,
    name: 'TONGA',
    iso: 'TO',
    iso3: 'TON',
    icon: null,
    numcode: 776,
    phoneCode: 676,
  },
  {
    id: 216,
    createdAt: null,
    updatedAt: null,
    name: 'TRINIDAD AND TOBAGO',
    iso: 'TT',
    iso3: 'TTO',
    icon: null,
    numcode: 780,
    phoneCode: 1868,
  },
  {
    id: 217,
    createdAt: null,
    updatedAt: null,
    name: 'TUNISIA',
    iso: 'TN',
    iso3: 'TUN',
    icon: null,
    numcode: 788,
    phoneCode: 216,
  },
  {
    id: 218,
    createdAt: null,
    updatedAt: null,
    name: 'TURKEY',
    iso: 'TR',
    iso3: 'TUR',
    icon: null,
    numcode: 792,
    phoneCode: 90,
  },
  {
    id: 219,
    createdAt: null,
    updatedAt: null,
    name: 'TURKMENISTAN',
    iso: 'TM',
    iso3: 'TKM',
    icon: null,
    numcode: 795,
    phoneCode: 7370,
  },
  {
    id: 220,
    createdAt: null,
    updatedAt: null,
    name: 'TURKS AND CAICOS ISLANDS',
    iso: 'TC',
    iso3: 'TCA',
    icon: null,
    numcode: 796,
    phoneCode: 1649,
  },
  {
    id: 221,
    createdAt: null,
    updatedAt: null,
    name: 'TUVALU',
    iso: 'TV',
    iso3: 'TUV',
    icon: null,
    numcode: 798,
    phoneCode: 688,
  },
  {
    id: 222,
    createdAt: null,
    updatedAt: null,
    name: 'UGANDA',
    iso: 'UG',
    iso3: 'UGA',
    icon: null,
    numcode: 800,
    phoneCode: 256,
  },
  {
    id: 223,
    createdAt: null,
    updatedAt: null,
    name: 'UKRAINE',
    iso: 'UA',
    iso3: 'UK',
    icon: null,
    numcode: 804,
    phoneCode: 380,
  },
  {
    id: 224,
    createdAt: null,
    updatedAt: null,
    name: 'UNITED ARAB EMIRATES',
    iso: 'AE',
    iso3: 'ARE',
    icon: null,
    numcode: 784,
    phoneCode: 971,
  },
  {
    id: 225,
    createdAt: null,
    updatedAt: null,
    name: 'UNITED KINGDOM',
    iso: 'GB',
    iso3: 'GBR',
    icon: null,
    numcode: 826,
    phoneCode: 44,
  },
  {
    id: 226,
    createdAt: null,
    updatedAt: null,
    name: 'UNITED STATES',
    iso: 'US',
    iso3: 'USA',
    icon: null,
    numcode: 840,
    phoneCode: 1,
  },
  {
    id: 227,
    createdAt: null,
    updatedAt: null,
    name: 'UNITED STATES MINOR OUTLYING ISLANDS',
    iso: 'UM',
    iso3: 'N/A',
    icon: null,
    numcode: 0,
    phoneCode: 1,
  },
  {
    id: 228,
    createdAt: null,
    updatedAt: null,
    name: 'URUGUAY',
    iso: 'UY',
    iso3: 'URY',
    icon: null,
    numcode: 858,
    phoneCode: 598,
  },
  {
    id: 229,
    createdAt: null,
    updatedAt: null,
    name: 'UZBEKISTAN',
    iso: 'UZ',
    iso3: 'UZB',
    icon: null,
    numcode: 860,
    phoneCode: 998,
  },
  {
    id: 230,
    createdAt: null,
    updatedAt: null,
    name: 'VANUATU',
    iso: 'VU',
    iso3: 'VUT',
    icon: null,
    numcode: 548,
    phoneCode: 678,
  },
  {
    id: 231,
    createdAt: null,
    updatedAt: null,
    name: 'VENEZUELA',
    iso: 'VE',
    iso3: 'VEN',
    icon: null,
    numcode: 862,
    phoneCode: 58,
  },
  {
    id: 232,
    createdAt: null,
    updatedAt: null,
    name: 'VIET NAM',
    iso: 'VN',
    iso3: 'VNM',
    icon: null,
    numcode: 704,
    phoneCode: 84,
  },
  {
    id: 233,
    createdAt: null,
    updatedAt: null,
    name: 'VIRGIN ISLANDS, BRITISH',
    iso: 'VG',
    iso3: 'VGB',
    icon: null,
    numcode: 92,
    phoneCode: 1284,
  },
  {
    id: 234,
    createdAt: null,
    updatedAt: null,
    name: 'VIRGIN ISLANDS, U.S.',
    iso: 'VI',
    iso3: 'VIR',
    icon: null,
    numcode: 850,
    phoneCode: 1340,
  },
  {
    id: 235,
    createdAt: null,
    updatedAt: null,
    name: 'WALLIS AND FUTUNA',
    iso: 'WF',
    iso3: 'WLF',
    icon: null,
    numcode: 876,
    phoneCode: 681,
  },
  {
    id: 236,
    createdAt: null,
    updatedAt: null,
    name: 'WESTERN SAHARA',
    iso: 'EH',
    iso3: 'ESH',
    icon: null,
    numcode: 732,
    phoneCode: 212,
  },
  {
    id: 237,
    createdAt: null,
    updatedAt: null,
    name: 'YEMEN',
    iso: 'YE',
    iso3: 'YEM',
    icon: null,
    numcode: 887,
    phoneCode: 967,
  },
  {
    id: 238,
    createdAt: null,
    updatedAt: null,
    name: 'ZAMBIA',
    iso: 'ZM',
    iso3: 'ZMB',
    icon: null,
    numcode: 894,
    phoneCode: 260,
  },
  {
    id: 239,
    createdAt: null,
    updatedAt: null,
    name: 'ZIMBABWE',
    iso: 'ZW',
    iso3: 'ZWE',
    icon: null,
    numcode: 716,
    phoneCode: 263,
  },
]
